/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=WorkerBindings src/bindings.d.ts` (hash: 49ef392c2499050c5fcc8b901b6b87f0)
interface __BaseEnv_WorkerBindings {
	SHARES: KVNamespace;
	AI_RATE_LIMIT: RateLimit;
	LOGIN_RATE_LIMIT: RateLimit;
	ASSETS: Fetcher;
	AI_ENABLED: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AI_ENABLED">> {}
}
