/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=WorkerBindings src/bindings.d.ts` (hash: 0e616e47dd3143483b3fedff3e51c04f)
interface __BaseEnv_WorkerBindings {
	SHARES: KVNamespace;
	DB?: D1Database;
	AI_RATE_LIMIT: RateLimit;
	LOGIN_RATE_LIMIT: RateLimit;
	ASSETS: Fetcher;
	AI_ENABLED: string;
	AUTH_MODE?: string;
	ACCESS_TEAM_DOMAIN?: string;
	ACCESS_AUD?: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface StagingEnv {
		SHARES: KVNamespace;
		DB: D1Database;
		AI_RATE_LIMIT: RateLimit;
		LOGIN_RATE_LIMIT: RateLimit;
		ASSETS: Fetcher;
		AI_ENABLED: string;
		AUTH_MODE: string;
		ACCESS_TEAM_DOMAIN: string;
		ACCESS_AUD: string;
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AI_ENABLED" | "AUTH_MODE" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD">> {}
}
